# Generated by Django 5.2.1 on 2025-06-16 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('artist', models.CharField(max_length=160)),
                ('album', models.CharField(blank=True, max_length=160, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('liked', models.ManyToManyField(blank=True, related_name='liked_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
