# Generated by Django 5.2.1 on 2025-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
