# Generated by Django 5.2.1 on 2025-06-09 21:02

import app3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_playlist_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(blank=True, default='playlist_images/default_playlist.png', null=True, upload_to=app3.models.playlist_image_path),
        ),
    ]
