# Generated by Django 5.2.1 on 2025-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0004_song_lyrics_alter_playlist_image_alter_song_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="playlist_images/"
            ),
        ),
    ]
